### ISSUE TITLE
Can obow work in non-iconic image datasets like COCO?

### ISSUE THREAD

**Issue by guanfuchen** [valeoai/obow#1]
I see it uses bow, so can it conver the problem which contrastive-base methods work not perfect in non-iconic image datasets like COCO?

![image](https://user-images.githubusercontent.com/22321977/105799403-69a19c00-5fcf-11eb-874b-5898ab731346.png)

**Comment by abursuc** [comment]
Hi @guanfuchen!

Thanks for the interest in our work and sorry for the late reply -- we have a glitch with our account and didn't see notifications :(

Yes, OBoW can be extended to other non-object centric datasets. This is an benefit of feature reconstruction methods such as OBoW, BYOL, BoWNet, as they focus on reconstructing the features of the image itself and not on discriminating the (object centered) image from other images in the dataset, as done in contrastive methods.  

There should not be major changes in the OBoW pipeline to extend it to other datasets. Depending on the content and size of the datasets, the size of the dictionary could benefit from some tuning.
