### ISSUE TITLE
About indoor usage

### ISSUE THREAD

**Issue by oym1994** [valeoai/obow#4]
Hi, thanks for your great contribution. Here I want to consult some questions about indoor experiment.

In the paper, all experements are conducted in public datasets and most are for object detection and classification. I wander what would be the difference if applying it into a real indoor environment to help slam relocalization and loop detection, such as home, official and even some room with repeat region(such as a Server Room where many server computers with the same appearance are placed)? What should I care about when collecting training data?
Thanks for your attention and I am always looking forward to your kind response and any advice.

Best, Slamer

**Comment by abursuc** [comment]
Hi @oym1994 !

Thanks for the interest in this work.
Indeed, OBoW can be used for pre-training on other datasets. 
Like all unsupervised methods, the quality of the outcome is dependent on the quality of the training data: quantity, diversity, balance, etc. These are the main things to take into consideration when you generate your own dataset.

Then for such datasets, you can adjust the size of the OBoW vocabulary depending on the type of content you have. I would expect a smaller dictionary to work better here than we considered for ImageNet. There will be a trade-off to find for your dataset: smaller vocabulary leads to more invariant features, bigger vocabulary to bigger sensitivity and discrimination of various patterns in the images.
